name: agu2017
channels:
    - conda-forge/label/dev
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - pip
    - gmt=6.0.0a11
    - numpy
    - pandas
    - matplotlib
    - jupyter
    - pip:
        - https://github.com/GenericMappingTools/gmt-python/archive/5659bbdcffd9bf5491e200766c119f5151852778.zip
